name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Linux amd64
        run: go build -o drg-linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Build Linux arm64
        run: go build -o drg-linux-arm64
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Build Windows amd64
        run: go build -o drg-windows-amd64
        env:
          GOOS: windows
          GOARCH: amd64

      - name: Build macOS amd64
        run: go build -o drg-darwin-amd64
        env:
          GOOS: darwin
          GOARCH: amd64

      - name: Build macOS arm64
        run: go build -o drg-darwin-arm64
        env:
          GOOS: darwin
          GOARCH: arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            drg-linux-amd64
            drg-linux-arm64
            drg-windows-amd64
            drg-darwin-amd64
            drg-darwin-arm64
